---
  - name: Delete GPO directory if exists
    ansible.windows.win_file:
      path: '{{ win.directory.gpo }}'
      state: absent

  - name: Make sure GPO directory exists
    ansible.windows.win_file:
      path: '{{ win.directory.gpo }}'
      state: directory

  - name: Copy GPO container
    ansible.builtin.copy:
      src: files/GPO.zip
      dest: '{{ win.directory.gpo }}/GPO.zip'

  - name: Unzip GPO container
    community.windows.win_unzip:
      src: '{{ win.directory.gpo }}\GPO.zip'
      dest: '{{ win.directory.gpo }}\GPO'

  - name: Import GPO
    script: files/gpo-import.ps1
    args:
      creates: '{{ win.directory.logging }}\gpo-import.txt'